name: RIDE SHARING CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    name: Build, Package & Deploy Microservice
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v3

     
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

    
      - name: 🔓 Make gradlew executable
        run: chmod +x ./gradlew

     
      - name: Build project with Gradle
        run: ./gradlew clean build -x test

     
      - name: Build Docker image
        run: docker build -t myuser/myservice:latest .

     
      - name: Push image to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push myuser/myservice:latest

     
      - name: Deployment step
        run: echo "Triggering deployment to environment... (Add your logic here)"
